 version: "3.8"
 services:
   mysql_server:
     build: ./db 
     command: mysqld --default-authentication-plugin=mysql_native_password
     restart: always
     environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: mysql-blog
          #  MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
   backend-mysql:
     depends_on:
       - mysql_server
     build: .
     environment:
       MYSQL_DATABASE: mysql-blog
       MYSQL_USER: root
       MYSQL_PASSWORD: root
       MYSQL_HOST: mysql_server # needs to be enclosed with quotes
     links: 
       - mysql_server
     ports:
       - "3001:3001"
     restart: always
  

