version: "3"
services:
  web:
    image: wonderviolet/server
    build: .
    command: "node server.js"
    ports:
      - "10000:5000"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes: 
      - "./mongo:/data/db"