 version: "3.8"
 services:
   mysql_server:
     image: arm64v8/mysql:oracle 
     env_file: ./.env
     restart: always
     command: --default-authentication-plugin=mysql_native_password
     ports:
      - "3306:3306"
     environment:
           MYSQL_ROOT_PASSWORD: root
           MYSQL_DATABASE: mysql-blog
           MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
   backend-mysql:
     image: violettaryabtsev/docker-app:5.0
     container_name: "mysql-server"
     depends_on:
       - mysql_server
     build: .
     command: bash -c 'while !</dev/tcp/mysql_server/3306; do sleep 1; done; npm start'
     environment:
       MYSQL_URL: mysql_server
       DB_HOST: mysql_server
       MYSQL_PASSWORD: test_pass
       MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
     restart: always
     links: 
       - mysql_server
     ports:
       - "3001:3001"
  

